apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: net410-kops-busybox
  labels:
    app: net410-kops-busybox
spec:
  replicas: 2 # tells deployment to run 3 pods matching the template
  selector:
    matchLabels:
      app: net410-kops-busybox
  template:
    metadata:
      labels:
        app: net410-kops-busybox
    spec:
      containers:
      - name: net410-kops-busybox
        image: busybox
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
