kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: simple-http-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-http-server-pod
  template:
    metadata:
      labels:
        app: simple-http-server-pod
    spec:
      containers:
      - name: simple-http
        image: python:2.7
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["-c", "echo \"<p>Hello from $(hostname), welcome to NET410 Workshop</p>\" > index.html; python -m SimpleHTTPServer 8080"]
        ports:
        - name: http
          containerPort: 8080
